### ISSUE TITLE
Having trouble when debuging model_main.py

### ISSUE THREAD

**Issue by cydiachen** [ZhuYun97/ShuffleNetv2-YOLOv3#1]
Dear author:
        Thank you for implementing the nice and elegant pytorch version YOLO v3 with ShuffleNet V2 backbone, I am now working on my own project, so I have to reorganize your project, I noticed that when debugging model_main.py file, The shufflenet cannot get right  number of states in the right place: 
![QQ截图20190718180825](https://user-images.githubusercontent.com/26337720/61449248-19cc2880-a987-11e9-8acf-80ceb5acbc8d.png)
Would you mind check the inside detail on stages and give me some advices?

**Comment by ZhuYun97** [comment]
I have update the codes, and I can run smoothly. @cydiachen

**Comment by ZhuYun97** [comment]
I have updated the codes, and it can run smoothly.
